export const GET_USER_INFO = 'GET_USER_INFO';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';
export const FETCH_USER_REPO_SUCCESS = 'FETCH_USER_REPO_SUCCESS';
export const FETCH_USER_REPO_FAILURE = 'FETCH_USER_REPO_FAILURE';